// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import svelte from '@astrojs/svelte';
import { readFileSync } from 'node:fs';
import { base, site } from './scripts/site-base.mjs';

// Topic groups generated by scripts/import-python-course.py
const programmingFundamentals = JSON.parse(
	readFileSync(new URL('./scripts/programming-fundamentals.sidebar.json', import.meta.url), 'utf8'),
);

// https://astro.build/config
export default defineConfig({
	// Hosting address: edit scripts/site-base.mjs. Used for the sitemap, canonical links and the base path.
	site,
	base,
	integrations: [
		starlight({
			title: 'Software Development Resources',
			description:
				'A repository with code comments on exercises and assignments.',
			logo: {
				src: './src/assets/logo.svg',
				replacesTitle: false,
			},
			favicon: '/favicon.svg',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/bmanke/SDEV-Resources' },
			],
			editLink: {
				baseUrl: "https://github.com/bmanke/SDEV-Resources/edit/main/",
			},
			lastUpdated: true,
			customCss: [
				'@fontsource-variable/inter',
				'@fontsource-variable/jetbrains-mono',
				'./src/styles/custom.css',
			],
			// Swap or extend any built-in Starlight component.
			components: {
				PageTitle: './src/components/overrides/PageTitle.astro',
			},
			// Full-text search is powered by Pagefind and is ON by default.
			// It indexes the site during `astro build` (search is unavailable in `astro dev`).
			pagefind: true,
			sidebar: [
				{
					label: 'First Semester',
					items: [
						{
							label: 'Programming Fundamentals',
							items: programmingFundamentals.map((t) => ({
								label: t.label,
								collapsed: true,
								items: [{ autogenerate: { directory: t.dir } }],
							})),
						},
						{
							label: 'Frontend Development',
							items: [
								{
									label: 'Lessons',
									items: [{ autogenerate: { directory: 'getting-started/frontend-development/lessons' } }],
								},
								{
									label: 'Resources',
									collapsed: true,
									items: [{ autogenerate: { directory: 'getting-started/frontend-development/resources' } }],
								},
							],
						},
					],
				},
				{
					label: 'Second Semester',
					items: [
						{
							label: 'SDEV-2150 Intermediate Frontend',
							items: [
								{
									label: 'Exercises',
									items: [{ autogenerate: { directory: 'sdev-2150-intermediate-frontend/exercises' } }],
								},
							],
						},
						{
							label: 'SDEV-2401 Rapid Backend Development',
							items: [{ autogenerate: { directory: 'sdev-2401-rapid-backend' } }],
						},
					],
				},
				{ label: 'Changelog', slug: 'changelog' },
			],
		}),
		svelte(),
	],
});
